language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      dist: xenial
      env:
        - TOXENV=py36
        - AUTOGRAPH_INTEGRATION=1
        - JAVA_HOME=/usr/lib/jvm/java-8-oracle
      sudo: true
    - python: 3.7
      dist: xenial
      env:
        - TOXENV=py37
        - AUTOGRAPH_INTEGRATION=1
        - JAVA_HOME=/usr/lib/jvm/java-8-oracle
      sudo: true

before_install:
    # Install oracle java 8, because jarsigner in openjdk 11.0.1+13 breaks
    # integration tests.
    # https://github.com/mozilla-releng/signingscript/issues/80
    - sudo add-apt-repository -y ppa:webupd8team/java
    - sudo apt-get update
    - echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    - echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    - sudo apt-get install oracle-java8-installer
install:
    - travis_retry pip install tox
    - sudo apt-get install zipalign
script:
    - docker run --name autograph -d -p 5500:5500 -v $(pwd)/signingscript/test/data/:/data/ mozilla/autograph:2.5.0 /go/bin/autograph -c /data/autograph_server_test_config.yaml
    - tox
after_script:
    - docker stop autograph
    - tox -e coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
