language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7-dev
      env: TOXENV=py37
  allow_failures:
    - python: 3.7-dev

install:
    - travis_retry pip install tox
script:
    - tox
after_success:
    - tox -e coveralls

# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
