version: '3'
services:
  cli:
    build: '.'
    tty: true
    command: '/bin/bash'
    environment:
      - PATH=/app/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

